export interface New {
    id: number,
    position: number,
    nameUz: string,
    nameRu: string,
    nameEn: string,
    descriptionRu: string,
    descriptionUz: string,
    descriptionEn: string,
    image: string,
    created: string|null,
    createdAt: string,
    updated: string|null,
    updatedAt: string,
  }
  export interface NewTypes {
    position: any,
    nameUz: string,
    nameRu: string,
    nameEn: string,
    descriptionRu: string,
    descriptionUz: string,
    descriptionEn: string,
    image: string,
  }