export interface Vacancy {
    id: number,
    nameUz: string,
    nameRu: string,
    nameEn: string,
    descriptionRu: string,
    descriptionUz: string,
    descriptionEn: string,
    image: string,
    isActive: any,
    region: string,
    requirementEn: string,
    requirementRu: string,
    requirementUz: string,
    responsibilityEn: string,
    responsibilityRu: string,
    responsibilityUz: string,
    typeEn: string,
    typeRu: string,
    typeUz: string,
    created: string|null,
    createdAt: string,
    updated: string|null,
    updatedAt: string,
  }
  export interface VacancyTypes {
    nameUz: string,
    nameRu: string,
    nameEn: string,
    descriptionRu: string,
    descriptionUz: string,
    descriptionEn: string,
    image: string,
    isActive: any,
    region: string,
    requirementEn: string,
    requirementRu: string,
    requirementUz: string,
    responsibilityEn: string,
    responsibilityRu: string,
    responsibilityUz: string,
    typeEn: string,
    typeRu: string,
    typeUz: string,
  }